### ISSUE TITLE
'flush_ms()' was not declared in this scope

### ISSUE THREAD

**Issue by Long-jm** [PervasiveDisplays/ePaper_EXT3_DrivingCode#1]
I can't find a declaration for flush_ms() in any of the files in the ePaper_EXT3_DrivingCode so when I compile the Common_Colours.ino (flush_ms() at line 169) example file and include the entire library, it pops up with this error. Can flush_ms() be replaced with myScreen.flush()?

**Comment by rei-vilo** [comment]
Thank you for reporting the issue. 

New [release 5.0.8](https://github.com/rei-vilo/PDLS_EXT3_Basic/releases/tag/5.0.8) fixes the issue with `myScreen.flush()`.

Alternatively, define `flush_ms()` as

```
///
/// @brief Flush screen and display time
///
void flush_ms()
{
    uint32_t chrono = (uint32_t)millis();
    myScreen.flush();
    Serial.println("%i ms", millis() - chrono);
}
```
